FROM tomcat:jdk8
ARG BAHMNI_REPORTS_URL=https://nexus.mekomsolutions.net/repository/maven-snapshots/org/bahmni/reports/0.92-SNAPSHOT/reports-0.92-20200206.093821-1.war
RUN apt-get update && \
    apt-get install wget mysql-client gettext-base -y && \
    mkdir -p /var/www/bahmni_config/ /root/.bahmni-reports/ && \
    wget -O /opt/mysql-connector-java-5.1.26.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/5.1.26/mysql-connector-java-5.1.26.jar && \
    wget -O /opt/liquibase-core-2.0.5.jar   https://repo1.maven.org/maven2/org/liquibase/liquibase-core/2.0.5/liquibase-core-2.0.5.jar && \
    wget -O /tmp/bahmni-reports.war ${BAHMNI_REPORTS_URL} && \
    mv /tmp/bahmni-reports.war /usr/local/tomcat/webapps/bahmni-reports.war
ADD scripts/ /etc/scripts/
ADD conf/ /opt/conf/
VOLUME /reports
RUN chmod +x /etc/scripts/*
CMD ["/bin/sh", "/etc/scripts/setup.sh"]