services:
  odoo-initialize-bahmni-addons:
    build: ../bahmni-odoo
    depends_on:
      - odoo-postgresql
    environment:
      HOST: odoo-postgresql
      PORT: 5432
      USER: odoo
      PASSWORD: odoo
    command: "-d odoo -i base,web_readonly_bypass,bahmni_web_extension,bahmni_product,bahmni_account,bahmni_sale,bahmni_stock,bahmni_atom_feed,bahmni_purchase"
    networks:
      bahmni:
    ports:
      - "8069:8069"
    volumes:
      - odoo-filestore:/var/lib/odoo/filestore

  odoo-postgresql:
    image: postgres:10
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d postgres"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      bahmni:
    volumes:
      - odoo-postgresql-data:/var/lib/postgresql/data

version: "3.7"
volumes:
  odoo-postgresql-data:
    external: true
  odoo-filestore:
    external: true
networks:
  bahmni:
